apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: microfrontend-controller
  namespace: microfrontends-controller-system
spec:
  parentRefs:
    - name: wac-hospital-gateway
      namespace: wac-hospital
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ui
      backendRefs:
        - group: ""
          kind: Service
          name: microfrontends-controller-manager
          port: 80