apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: microfrontend-controller-go
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/SevcikMichal/wacdemo-ambulance-gitops 