apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
 app.kubernetes.io/part-of: wac-hospital
namespace: wac-hospital
resources:
- prepare.kustomization.yaml
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml
- wacdemo-ambulance-ufe.image-repository.yaml 
- wacdemo-ambulance-ufe.image-policy.yaml 
- ufe-controller.image-repository.yaml 
- ufe-controller.image-policy.yaml 
- microfrontend-controller.image-repository.yaml 
- microfrontend-controller.image-policy.yaml 
- microfrontend-webui.image-repository.yaml 
- microfrontend-webui.image-policy.yaml 
- image-update-automation.yaml 
- wacdemo-ambulance-webapi.image-repository.yaml
- wacdemo-ambulance-webapi.image-policy.yaml