apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: microfrontend-webui
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: microfrontend-webui
  policy:
    semver:
      range: "^v0.*.*"