apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: microfrontend-controller
  namespace: wac-hospital
spec:
  image: sevcikmichal/microfrontends-controller
  interval: 15m0s