apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: polyfea-controller
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: polyfea-controller # referuje ImageRepository z predchádzajúceho kroku
  policy:
    semver:
      range: "^0.*.*"