apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: msevcik/wacdemo-ambulance-ufe
  newName: msevcik/wacdemo-ambulance-ufe # {"$imagepolicy":  "wac-hospital:wacdemo-ambulance-ufe:name"} 
  newTag: main.20231025.1148 # {"$imagepolicy": "wac-hospital:wacdemo-ambulance-ufe:tag"} 
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"} 
  newTag: 1.6.6 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
