apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital
  app.kubernetes.io/name: wacdemo-ambulance-wl

resources:
- ../../../apps/wacdemo-ambulance-ufe
- ../../../apps/wacdemo-ambulance-webapi


components:
- ../../../components/version-release

patches:
- target:
    group: polyfea.github.io
    version: v1alpha1
    kind: MicroFrontend
    name: wacdemo-ambulance-ufe
  patch: |-
    apiVersion: polyfea.github.io/v1alpha1
    kind: MicroFrontend
    metadata:
      name: wacdemo-ambulance-ufe
    spec:
      frontendClass: "wac-hospital"