apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/wacdemo-ambulance-ufe
- ../../../apps/polyfea-md-shell

patches:
- path: patches/material-design.microfrontend.yaml
- path: patches/polyfea-md-shell.microfrontend.yaml