apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/wacdemo-ambulance-ufe
- ../../../apps/wacdemo-ambulance-webapi
- ../../../apps/polyfea-md-shell
- ../../../apps/mongo-express

patches:
- path: patches/material-design.microfrontend.yaml
- path: patches/polyfea-md-shell.microfrontend.yaml
- path: patches/ambulance-webapi.service.yaml
- path: patches/polyfea-fea.microfrontendclass.yaml

components:
- ../../../components/version-developers
- https://github.com/SevcikMichal/wacdemo-ambulance-webapi///deployments/kustomize/components/mongodb
