apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wac-hospital
commonLabels:
  app.kubernetes.io/part-of: wac-hospital
resources:
- ../../../apps/wacdemo-ambulance-ufe
- ../../../apps/wacdemo-ambulance-webapi
components: 
- ../../../components/version-developers
- https://github.com/sevcikmichal/wacdemo-ambulance-webapi//deployments/kustomize/components/mongodb
patches:
- path: patches/wacdemo-ambulance-webapi.service.yaml