apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../infrastructure/polyfea-controller
- ../../../infrastructure/fluxcd

patches:
- path: patches/polyfea-controller.service.yaml

components:
- ../../../components/version-developers