apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../infrastructure/ufe-controller
- ../../../infrastructure/microfrontend-controller
- ../../../infrastructure/fluxcd
patches: 
- path: patches/ufe-controller.service.yaml
- path: patches/microfrontend-controller.service.yaml
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: "HTTP_CSP_HEADER"
        value: "default-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://fonts.gstatic.com/; font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/; script-src 'nonce-{NONCE_VALUE}'; connect-src 'self' localhost:30331 localhost:30081"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ufe-controller
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: "HTTP_CSP_HEADER"
        value: "default-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://fonts.gstatic.com/; font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/; script-src 'nonce-{NONCE_VALUE}'; connect-src 'self' localhost:30332 localhost:30081"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: microfrontends-controller-controller-manager
components: 
 - ../../../components/version-developers