apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../infrastructure/ufe-controller
- ../../../infrastructure/microfrontend-controller
- ../../../infrastructure/fluxcd
patches: 
- path: patches/ufe-controller.service.yaml
- path: patches/microfrontend-controller.service.yaml
components: 
 - ../../../components/version-developers