apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/polyfea/polyfea-controller//config/default
- http-route.yaml

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/component: polyfea-controller