apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/milung/ufe-controller//configs/k8s/kustomize
namespace: wac-hospital
commonLabels:
  app.kubernetes.io/component: ufe-controller
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: "HTTP_CSP_HEADER"
        value: "default-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://fonts.gstatic.com/; font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/; script-src 'nonce-{NONCE_VALUE}'; connect-src 'self' localhost:30331 localhost:30081"
  target:
    kind: Deployment
    namespace: ufe-controller
    name: wac-hospital