apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: wacdemo-ambulance-ufe-content
spec:
  element: iframe
  attributes:
    - name: src
      value: /mongo-express
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mongo-express(/.*)?$"
