apiVersion: microfrontend.michalsevcik.dev/v1alpha1
kind: WebComponent
metadata:
  name: mongo-express
spec:
  module-uri: built-in
  navigations:
    - element: ufe-frame
      path: mongo-express
      title: Mongo Express
      details: UI Access to local Mongo DB
      attributes:
        - name: src
          value: /mongo-express