apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- webcomponent.yaml
- webcomponent-go.yaml
commonLabels:
  app.kubernetes.io/component: wacdemo-ambulance-ufe