kind: Service
apiVersion: v1
metadata:
  name: wacdemo-ambulance-ufe
spec:  
  selector:
    pod: wacdemo-ambulance-ufe-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http