apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: wacdemo-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes: 
    - name: headline
      value: Zoznam čakajúcich wacdemo
    - name: short-headline
      value: Zoznam čakajúcich wacdemo
    - name: supporting-text
      value: |
        Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
    - name: material-icon
      value: home_health
    - name: href
      value: ./wacdemo-ambulance-wl
  priority: 10
  displayRules:
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content