apiVersion: microfrontend.michalsevcik.dev/v1alpha1
kind: WebComponent
metadata: 
  name: wacdemo-ambulance-ufe
spec:   
  module-uri: http://wacdemo-ambulance-ufe.wac-hospital/build/ambulance-ufe.esm.js  
  navigations:
    - element: wacdemo-ambulance-wl-list
      path: wacdemo-ambulance-wl
      title: Zoznam čakajúcich wacdemo
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false
  proxy: true
  hash-suffix: v1alpha1