apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: wacdemo-ambulance-ufe-content
spec:
  microFrontend: wacdemo-ambulance-ufe
  element: wacdemo-ambulance-wl-app
  attributes:
    - name: base-path
      value: /wacdemo-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?wacdemo-ambulance-wl(/.*)?$"
