apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: wacdemo-ambulance-ufe
spec:   
  module-uri: http://wacdemo-ambulance-ufe.wac-hospital/build/ambulance-ufe.esm.js  
  navigation:
    - element: wacdemo-ambulance-wl-app
      path: wacdemo-ambulance-wl
      title: Zoznam čakajúcich wacdemo
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false
  proxy: true
  hash-suffix: v1alpha1